/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poscihazı;

import Actions.action;
import com.sun.prism.j2d.J2DPipeline;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javafx.scene.layout.Border;
import javax.swing.Action;
import javax.swing.ImageIcon;
import javax.swing.JFrame;            //Pencere nesnesi oluşturabilmemiz için içe aktarmamız gereken sınıf
import javax.swing.JPanel;            //Panel nesnesi oluşturabilmemiz için içe aktarmamız gereken sınıf
import javax.swing.JButton;           //Buton nesnesi oluşturabilmemiz için içe aktarmamız gereken sınıf
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;        //TextField nesnesi oluşturabilmemiz için içe aktarmamız gereken sınıf
import javax.swing.JPasswordField;    //PasswordField nesnesi oluşturabilmemiz için içe aktarmamız gereken sınıf
import javax.swing.JLabel;
import static javax.swing.text.html.HTML.Tag.IMG;
import sun.audio.*;

/**
 *
 * @author Kubra
 */
public class poscihazi {

    action a1 = null;

    public action getA1() {
        if (a1 == null) {
            a1 = new action(this);
        }
        return a1;
    }

    public void setA1(action a1) {
        this.a1 = a1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor. //
     */
//    //Actions a=new Actions();
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 400, Short.MAX_VALUE)
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 300, Short.MAX_VALUE)
//        );
//        pack();
//    }
    // </editor-fold>//GEN-END:initComponents
    JFrame frame;
    JButton getAsagi;
    JButton yukari;
    JButton kirmizi;
    JButton getSari;
    JButton yesil;
    JPanel birustpanel;
    JPanel endispanel;
    JPanel usttekipanel;
    JPanel ortapanell;
    JLabel satistutar;
    JLabel getSifree;
    JLabel arka;
    JButton getUst_label;
    JButton alt_label;
    JLabel bosluklabel;
    JLabel pin;
    JLabel okutulacakkart;
    JButton garanti;
    JButton ziraatbank;
    JButton isbanka;
    JPasswordField getSifre1;
    JLabel slipp;
    JLabel kartoku;
    JButton getButton3, getButton4, getButton5, getButton6, getButton7, getButton8, getButton9, getButton1, getButton2, getButton0, yildiz, diyez;

    public poscihazi() {
        frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setBounds(200, 200, 700, 1000);
        ImageIcon background = new ImageIcon("poscihazi\\poscihaz.PNG");
        ImageIcon kart = new ImageIcon("poscihazi\\parametleri\\garanti.png");
        ImageIcon ziraat = new ImageIcon("poscihazi\\parametleri\\ziraat.png");
        ImageIcon isbank = new ImageIcon("poscihazi\\parametleri\\işbank.png");
        ImageIcon girisarka = new ImageIcon("poscihazi\\parametleri\\girisekran.png");
        ImageIcon slip = new ImageIcon("poscihazi\\parametleri\\slip.png");

        birustpanel = new JPanel();
        JLabel label = new JLabel();
        arka = new JLabel();
        arka.setIcon(girisarka);
        label.setIcon(background);
        garanti = new JButton();
        garanti.setIcon(kart);
        ziraatbank = new JButton();
        ziraatbank.setIcon(ziraat);
        isbanka = new JButton();
        isbanka.setIcon(isbank);
        kartoku = new JLabel();
        kartoku.setText("OKUTULACAK KARTINIZI SEÇİNİZ: ");
        okutulacakkart = new JLabel();
        slipp = new JLabel();
        slipp.setIcon(slip);
        birustpanel.setBounds(230, 0, 220, 540);
        birustpanel.add(label);
        usttekipanel = new JPanel();
        usttekipanel.setBounds(251, 80, 167, 134);
        usttekipanel.setBackground(Color.white);
        usttekipanel.setVisible(true);
        endispanel = new JPanel();
        endispanel.setLayout(null);

        usttekipanel.add(arka);
        // Paneli oluşturuyorum
        ortapanell = new JPanel();
        ortapanell.setLayout(null);

        garanti.setBounds(500, 0, 300, 180);
        ziraatbank.setBounds(850, 0, 300, 180);
        isbanka.setBounds(680, 190, 300, 180);
        kartoku.setBounds(680, 200, 300, 180);

        slipp.setBounds(450, 380, 300, 300);
        yukari = new JButton();
        yukari.setBounds(290, 240, 40, 40);
        yukari.setForeground(Color.white);
        yukari.setBackground(Color.LIGHT_GRAY);
        getAsagi = new JButton();
        getAsagi.setBounds(335, 240, 40, 40);
        getAsagi.setForeground(Color.white);
        getAsagi.setBackground(Color.LIGHT_GRAY);
        getUst_label = new JButton();
        getUst_label.setText("Kredi Kartı                                   ");
        getUst_label.setBackground(Color.WHITE);
        getUst_label.setForeground(Color.black);
        getUst_label.setVisible(false);
        bosluklabel = new JLabel();
        bosluklabel.setVisible(false);
        alt_label = new JButton();
        alt_label.setText("Banka Kartı                                    ");
        alt_label.setVisible(false);
        alt_label.setBackground(Color.WHITE);
        alt_label.setForeground(Color.BLACK);
        satistutar = new JLabel();
        satistutar.setText("   SATIŞ TUTARINI GİRİNİZ:   ");

        satistutar.setBounds(20, 20, 40, 40);

        getSifree = new JLabel();
        getSifree.setText("0,00");
        pin = new JLabel();
        getSifree.setVisible(false);
        satistutar.setVisible(false);
        pin.setText(" pini giriniz:  ");
        pin.setBounds(20, 20, 40, 40);
        pin.setVisible(false);
        getSifre1 = new JPasswordField("");
        getSifre1.setBounds(310, 120, 50, 20);

        getSifre1.setVisible(false);

        // Nesneleri oluşturuyorum
        getButton1 = new JButton("1");
        getButton1.setBackground(Color.LIGHT_GRAY);

        getButton1.setBackground(Color.LIGHT_GRAY);
        getButton1.setForeground(Color.white);
        getButton1.setBounds(255, 290, 50, 50);

        Font bSize12 = new Font("Arial", Font.PLAIN, 25);
        slipp.setVisible(false);
        getButton2 = new JButton("2");
        getButton2.setForeground(Color.white);

        getButton2.setBackground(Color.LIGHT_GRAY);
        getButton2.setBounds(310, 290, 50, 50);
        getButton3 = new JButton("3");

        getButton3.setBackground(Color.LIGHT_GRAY);
        getButton3.setForeground(Color.white);
        getButton3.setBounds(365, 290, 50, 50);
        getButton4 = new JButton("4");
        getButton4.setForeground(Color.white);
        getButton4.setBackground(Color.LIGHT_GRAY);
        getButton4.setBounds(255, 340, 50, 50);
        getButton5 = new JButton("5");
        getButton5.setForeground(Color.white);
        getButton5.setBounds(310, 340, 50, 50);
        getButton5.setBackground(Color.LIGHT_GRAY);
        getButton6 = new JButton("6");
        getButton6.setBackground(Color.LIGHT_GRAY);
        getButton6.setForeground(Color.white);
        getButton6.setBounds(365, 340, 50, 50);
        getButton7 = new JButton("7");
        getButton7.setForeground(Color.white);
        getButton7.setBackground(Color.LIGHT_GRAY);
        getButton7.setBounds(255, 390, 50, 50);
        getButton8 = new JButton("8");
        getButton8.setForeground(Color.white);
        getButton8.setBackground(Color.LIGHT_GRAY);
        getButton8.setBounds(310, 390, 50, 50);
        getButton9 = new JButton("9");
        getButton9.setForeground(Color.white);
        getButton9.setBackground(Color.LIGHT_GRAY);
        getButton9.setBounds(365, 390, 50, 50);
        yildiz = new JButton("*");
        getButton9.setBackground(Color.LIGHT_GRAY);
        yildiz.setBounds(255, 442, 50, 40);

        getButton0 = new JButton("0");
        getButton0.setBounds(310, 442, 50, 40);
        getButton0.setForeground(Color.white);
        getButton0.setBackground(Color.LIGHT_GRAY);
        diyez = new JButton(".");
        diyez.setBounds(365, 442, 50, 40);
        kirmizi = new JButton();
        kirmizi.setBackground(Color.red);
        kirmizi.setBounds(257, 485, 45, 25);
        getSari = new JButton();
        getSari.setBackground(Color.yellow);
        getSari.setBounds(312, 485, 45, 25);
        yesil = new JButton();
        yesil.setBackground(Color.green);
        yesil.setBounds(367, 485, 45, 25);

        getButton0.setFont(bSize12);
        getButton1.setFont(bSize12);
        getButton2.setFont(bSize12);
        getButton3.setFont(bSize12);
        getButton4.setFont(bSize12);
        getButton5.setFont(bSize12);
        getButton6.setFont(bSize12);
        getButton7.setFont(bSize12);
        getButton8.setFont(bSize12);
        getButton9.setFont(bSize12);
        diyez.setFont(bSize12);

        yildiz.setFont(bSize12);

        // Nesneleri Panele ekliyorum
        ortapanell.add(getSifre1);
        ortapanell.add(getButton0);
        ortapanell.add(getButton9);
        ortapanell.add(getButton1);
        ortapanell.add(getButton2);
        ortapanell.add(getButton3);
        ortapanell.add(getButton4);
        ortapanell.add(getButton5);
        ortapanell.add(getButton6);
        ortapanell.add(getButton7);
        ortapanell.add(getButton8);
        ortapanell.add(yildiz);
        ortapanell.add(diyez);
        ortapanell.add(kirmizi);
        ortapanell.add(yesil);
        ortapanell.add(getSari);
        ortapanell.add(yukari);
        ortapanell.add(getAsagi);

        ortapanell.add(usttekipanel);
        ortapanell.add(birustpanel);
        ortapanell.add(garanti);
        ortapanell.add(ziraatbank);
        ortapanell.add(isbanka);
        ortapanell.add(kartoku);
        ortapanell.add(slipp);
        usttekipanel.add(satistutar);
        usttekipanel.add(getSifree);
        usttekipanel.add(getUst_label);
        usttekipanel.add(bosluklabel);
        usttekipanel.add(alt_label);
        usttekipanel.add(pin);

        getButton1.addActionListener(this.getA1());
        diyez.addActionListener(this.getA1());
        getButton2.addActionListener(this.getA1());

        getButton3.addActionListener(this.getA1());
        getButton4.addActionListener(this.getA1());
        getButton5.addActionListener(this.getA1());
        getButton6.addActionListener(this.getA1());
        getButton7.addActionListener(this.getA1());
        getButton8.addActionListener(this.getA1());
        getButton9.addActionListener(this.getA1());
        getButton0.addActionListener(this.getA1());
        yesil.addActionListener(this.getA1());
        kirmizi.addActionListener(this.getA1());
        yukari.addActionListener(this.getA1());
        getAsagi.addActionListener(this.getA1());
        getSari.addActionListener(this.getA1());
        ziraatbank.addActionListener(this.getA1());
        isbanka.addActionListener(this.getA1());
        garanti.addActionListener(this.getA1());

        //paneli Frame e ekliyorum
        frame.add(ortapanell);
        frame.setVisible(true);
//---&gt;&gt;&gt;frame.add(panel) ile aynı anlamı taşır
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    public JFrame getFrame() {
        return frame;
    }

    public void setFrame(JFrame frame) {
        this.frame = frame;
    }

    public JButton getAsagi() {
        return getAsagi;
    }

    public void setAsagi(JButton asagi) {
        this.getAsagi = asagi;
    }

    public JButton getYukari() {
        return yukari;
    }

    public void setYukari(JButton yukari) {
        this.yukari = yukari;
    }

    public JButton getKirmizi() {
        return kirmizi;
    }

    public void setKirmizi(JButton kirmizi) {
        this.kirmizi = kirmizi;
    }

    public JButton getSari() {
        return getSari;
    }

    public void setSari(JButton sari) {
        this.getSari = sari;
    }

    public JButton getYesil() {
        return yesil;
    }

    public void setYesil(JButton yesil) {
        this.yesil = yesil;
    }

    public JPanel getBirustpanel() {
        return birustpanel;
    }

    public void setBirustpanel(JPanel birustpanel) {
        this.birustpanel = birustpanel;
    }

    public JPanel getEndispanel() {
        return endispanel;
    }

    public void setEndispanel(JPanel endispanel) {
        this.endispanel = endispanel;
    }

    public JPanel getUsttekipanel() {
        return usttekipanel;
    }

    public void setUsttekipanel(JPanel usttekipanel) {
        this.usttekipanel = usttekipanel;
    }

    public JPanel getOrtapanell() {
        return ortapanell;
    }

    public void setOrtapanell(JPanel ortapanell) {
        this.ortapanell = ortapanell;
    }

    public JLabel getSatistutar() {
        return satistutar;
    }

    public void setSatistutar(JLabel satistutar) {
        this.satistutar = satistutar;
    }

    public JLabel getSifree() {
        return getSifree;
    }

    public void setSifree(JLabel sifree) {
        this.getSifree = sifree;
    }

    public JLabel getArka() {
        return arka;
    }

    public void setArka(JLabel arka) {
        this.arka = arka;
    }

    public JButton getUst_label() {
        return getUst_label;
    }

    public void setUst_label(JButton ust_label) {
        this.getUst_label = ust_label;
    }

    public JButton getAlt_label() {
        return alt_label;
    }

    public void setAlt_label(JButton alt_label) {
        this.alt_label = alt_label;
    }

    public JLabel getBosluklabel() {
        return bosluklabel;
    }

    public void setBosluklabel(JLabel bosluklabel) {
        this.bosluklabel = bosluklabel;
    }

    public JLabel getPin() {
        return pin;
    }

    public void setPin(JLabel pin) {
        this.pin = pin;
    }

    public JLabel getOkutulacakkart() {
        return okutulacakkart;
    }

    public void setOkutulacakkart(JLabel okutulacakkart) {
        this.okutulacakkart = okutulacakkart;
    }

    public JButton getGaranti() {
        return garanti;
    }

    public void setGaranti(JButton garanti) {
        this.garanti = garanti;
    }

    public JButton getZiraatbank() {
        return ziraatbank;
    }

    public void setZiraatbank(JButton ziraatbank) {
        this.ziraatbank = ziraatbank;
    }

    public JButton getIsbanka() {
        return isbanka;
    }

    public void setIsbanka(JButton isbanka) {
        this.isbanka = isbanka;
    }

    public JPasswordField getSifre1() {
        return getSifre1;
    }

    public void setSifre1(JPasswordField sifre1) {
        this.getSifre1 = sifre1;
    }

    public JLabel getSlipp() {
        return slipp;
    }

    public void setSlipp(JLabel slipp) {
        this.slipp = slipp;
    }

    public JButton getButton3() {
        return getButton3;
    }

    public void setButton3(JButton button3) {
        this.getButton3 = button3;
    }

    public JButton getButton4() {
        return getButton4;
    }

    public void setButton4(JButton button4) {
        this.getButton4 = button4;
    }

    public JButton getButton5() {
        return getButton5;
    }

    public void setButton5(JButton button5) {
        this.getButton5 = button5;
    }

    public JButton getButton6() {
        return getButton6;
    }

    public void setButton6(JButton button6) {
        this.getButton6 = button6;
    }

    public JButton getButton7() {
        return getButton7;
    }

    public void setButton7(JButton button7) {
        this.getButton7 = button7;
    }

    public JButton getButton8() {
        return getButton8;
    }

    public void setButton8(JButton button8) {
        this.getButton8 = button8;
    }

    public JButton getButton9() {
        return getButton9;
    }

    public void setButton9(JButton button9) {
        this.getButton9 = button9;
    }

    public JButton getButton1() {
        return getButton1;
    }

    public JLabel getKartoku() {
        return kartoku;
    }

    public void setKartoku(JLabel kartoku) {
        this.kartoku = kartoku;
    }

    public void setButton1(JButton button1) {
        this.getButton1 = button1;
    }

    public JButton getButton2() {
        return getButton2;
    }

    public void setButton2(JButton button2) {
        this.getButton2 = button2;
    }

    public JButton getButton0() {
        return getButton0;
    }

    public void setButton0(JButton button0) {
        this.getButton0 = button0;
    }

    public JButton getYildiz() {
        return yildiz;
    }

    public void setYildiz(JButton yildiz) {
        this.yildiz = yildiz;
    }

    public JButton getDiyez() {
        return diyez;
    }

    public void setDiyez(JButton diyez) {
        this.diyez = diyez;
    }

}
